### ISSUE TITLE
Style the Pet Match Form

### ISSUE THREAD

**Issue by davidgrieser** [kaylaswartz/PetMeProject#2]
Currently the form looks like classic HTML.

Find some forms on the web that you like and try to mimic the CSS for that form.
<img width="391" alt="PetMatchForm" src="https://user-images.githubusercontent.com/292375/129206634-84cafabe-6097-41c0-97ad-fd0040bc513e.png">

Example:
<img width="661" alt="StyledForm" src="https://user-images.githubusercontent.com/292375/129207064-9307eca7-5bbf-41c9-9086-3a7dfd8c3c4b.png">

**Comment by LisaGumbo** [comment]
@davidgrieser said we can close this issue because of **radio** buttons
