### ISSUE TITLE
Single index.js file

### ISSUE THREAD

**Issue by davidgrieser** [kaylaswartz/PetMeProject#3]
Previously you had all the JavaScript in 1 file and were experiencing issues with behavior.

Diving into commit df973ca I found the following:

<img width="643" alt="ScriptError" src="https://user-images.githubusercontent.com/292375/129207745-36956743-6f01-43c9-8c26-56252d43fec3.png">

As you develop JavaScript on a page, you'll want to always be on the look out for error from the code you write and write guard logic around it.

In this case you should be checking against `null` before you try to add an event listener.

This pattern repeats itself throughout the JavaScript

**Comment by kaylaswartz** [comment]
Could we get some clarification on checking against null?

**Comment by kaylaswartz** [comment]
Resolved this issue in branch JSMerge. JSMerge branch has been merged back to the master branch
