### ISSUE TITLE
Use pure CSS to style Dog and llama Information Pages

### ISSUE THREAD

**Issue by davidgrieser** [kaylaswartz/PetMeProject#4]
Similar to CSS Zen Garden, a page can pop once it has some additional styling.

Fancy: http://www.csszengarden.com/216/
Old School: http://www.csszengarden.com/218/
Artistic: http://www.csszengarden.com/217/

**Comment by kaylaswartz** [comment]
Updated and styled CSS pages - updates are in pull request: Use pure CSS to style Dog/llama Information Pages & Mixing http and https resource
