### ISSUE TITLE
Mixing http and https resource

### ISSUE THREAD

**Issue by davidgrieser** [kaylaswartz/PetMeProject#6]
![Screen Shot 2021-08-12 at 12 51 28 PM](https://user-images.githubusercontent.com/292375/129244843-b03e94c7-a6df-45fd-bac7-55ce532b7280.png)

**Comment by kaylaswartz** [comment]
addressed and remediated this issue in pull request: Use pure CSS to style Dog/llama Information Pages & Mixing http and https resource
